language: python
python:
  - "3.6.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip3 install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: coverage run --source=blog,djangoblog --omit=*migrations*,*tests*,djangoblog/wsgi* manage.py test
sudo: false
cache: pip

after_success: 
  - coveralls
  - codecov

env:
  global:
    - SECURE="adBS5Q2SLykuUBCYfYXCYZjk715I9aiJJ4A0+COPZkPsGKPmj9dTz4tfvlSEpHsG7C28ByMDnJj5FMJgssK+A+9ERRyIgwhwzkDiy4N+73HgkwwYEeYJv/STBxttbOSO3SrtFs7KJ7e2wg7cbvgVLT2gbWF+xiCMPrRHuWJGU80="
