language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: coverage run --source tdd --source blog manage.py test

after_success: coveralls

deploy:
  provider: heroku
  buildpack: python
  api_key: 1c26a711-07cf-47be-a337-c70df8498c75
  app: davidsdjango
  run: "python manage.py syncdb --noinput && python manage.py migrate"